baseURL = "https://horrorcash.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Mormo Zine | Links"
copyright = ""

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Mormo Zine"
  headline = "Make Money Online With Mormo - Everything Free Or One Dollar!"
  image = "img/shane.jpg"  # path relative to static directory

  links = [
    { link = { href = "https://youtu.be/H2UBS39RMhg", text = "Please Watch This Video FIRST!" } },
    { link = { href = "https://mormozine.gumroad.com/l/oBthb", text = "I create video content and want to make money [1$]" } },
    { link = { href = "https://mormozine.gumroad.com/l/DzFIy", text = "I'm a writer and want to make money [1$]" } },
    { link = { href = "https://mormozine.gumroad.com/l/zpZZL", text = "I want to be a horror influencer and make money [1$]" } },
    { link = { href = "https://trafficendgame.com/mormo", text = "I want to get more traffic. [FREE]" } },
    { link = { href = "https://lazycommissions.com/mormo", text = "I want to make money doing affiliate marketing [FREE]" } },
    { link = { href = "https://mormo.substack.com", text = "I want a glossy autographed photo of Mormo [FREE]" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = { href = "https://instagram.com/putyourusernamehereinsta", text = "Instagram" } },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = { href = "https://www.youtube.com/c/MormoZine", text = "YouTube" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
